### ISSUE TITLE
Cryptic message when missing a dependency

### ISSUE THREAD

**Issue by ecourreges-orange** [psycofdj/xtdmake#29]
Hello,
Here I had to look inside FindDocRule.cmake:12 to figure out that my missing dependency is Plantuml.
It would be more user friendly to have that in the error message instead of this:

> -- Found module StaticShared : FALSE (unmet required dependencies)
> -- Found program Doxygen : /usr/bin/doxygen (version "1.8.11")
> CMake Error at xtdmake/src/xtdmake_find_program.cmake:62 (if):
>   if given arguments:
> 
>     "STREQUAL" "1"
> 
>   Unknown arguments specified
> Call Stack (most recent call first):
>   xtdmake/src/doc/FindDocRule.cmake:12 (xtdmake_find_program)
>   xtdmake/src/XTDMakeConfig.cmake:41 (find_package)
>   CMakeLists.txt:68 (xtdmake_init)
> 
> 
> -- Configuring incomplete, errors occurred!
> 

Thank you,
Regards.

**Comment by psycofdj** [comment]
Hi,
Thanks for the issue

Fixed by PR #28 .
Remember to synchronize your local gitlab fork when the PR is merged.
