### ISSUE TITLE
support Ninja build

### ISSUE THREAD

**Issue by cangeli-orange** [psycofdj/xtdmake#31]
Great job with this tool !

But there is an error when I want to use Ninja:
`ninja: error: build.ninja:1510: bad $-escape (literal $ must be written as $$)`

It seems that it doesn't support the syntax :
https://github.com/psycofdj/xtdmake/blob/ff7e9bd224d7a9dd1a7c42abf408261cdb775b10/src/check/FindCheckRule.cmake#L272

Do you have a plan to support Ninja build, or is it sticked to Makefiles ?

**Comment by psycofdj** [comment]
XTDMake would sure benefit from supporting Ninja build system.
Would you mind submitting a PR with initial development ? I can help adding with acceptance tests to your branch.

**Comment by psycofdj** [comment]
closed by #32
